export type ReadingType = "Artigo" | "Livro" | "Artigo científico" | "Documento" | "Guia";
export type ReadingLevel = "Essencial" | "Intermediário" | "Avançado";

export type Reading = {
  id: string;
  title: string;
  author: string;
  source: string;
  type: ReadingType;
  category: "Negócios" | "Ideias" | "Mundo" | "Política" | "Fé" | "Ciência" | "Criação";
  level: ReadingLevel;
  language: "Português" | "Inglês";
  readTime: string;
  description: string;
  question: string;
  url: string;
  featured?: boolean;
};

export const readings: Reading[] = [
  {
    id: "feynman-power-of-teaching",
    title: "O poder de ensinar para aprender",
    author: "Caltech Center for Teaching, Learning & Outreach",
    source: "Caltech",
    type: "Guia",
    category: "Ciência",
    level: "Essencial",
    language: "Inglês",
    readTime: "8 min",
    description: "Um método inspirado em Richard Feynman: explicar em voz alta, localizar as lacunas e reconstruir a ideia com clareza.",
    question: "Em qual parte sua explicação fica vaga ou circular?",
    url: "https://ctlo.caltech.edu/aboutctlo/whoweserve/undergraduates/learning-resources/learning/power-of-teaching",
    featured: true,
  },
  {
    id: "aristotle-ethics",
    title: "A ética de Aristóteles",
    author: "Richard Kraut",
    source: "Stanford Encyclopedia of Philosophy",
    type: "Artigo",
    category: "Ideias",
    level: "Avançado",
    language: "Inglês",
    readTime: "55 min",
    description: "Virtude, felicidade, deliberação e sabedoria prática em uma introdução acadêmica ampla e referenciada.",
    question: "Qual hábito transforma uma regra abstrata em caráter?",
    url: "https://plato.stanford.edu/entries/aristotle-ethics/",
    featured: true,
  },
  {
    id: "rerum-novarum",
    title: "Rerum Novarum — sobre a condição dos trabalhadores",
    author: "Papa Leão XIII",
    source: "Santa Sé",
    type: "Documento",
    category: "Fé",
    level: "Intermediário",
    language: "Português",
    readTime: "45 min",
    description: "Texto fundamental da doutrina social católica sobre trabalho, propriedade, justiça, deveres e bem comum.",
    question: "Quais princípios permanecem válidos quando a forma do trabalho muda?",
    url: "https://www.vatican.va/content/leo-xiii/pt/encyclicals/documents/hf_l-xiii_enc_15051891_rerum-novarum.html",
    featured: true,
  },
  {
    id: "principles-management",
    title: "Principles of Management",
    author: "David S. Bright e Anastasia H. Cortes",
    source: "OpenStax",
    type: "Livro",
    category: "Negócios",
    level: "Intermediário",
    language: "Inglês",
    readTime: "Curso completo",
    description: "Livro-texto aberto sobre planejamento, organização, liderança, cultura, decisão e controle gerencial.",
    question: "Qual sistema permite que a equipe funcione sem depender de um herói?",
    url: "https://openstax.org/details/books/principles-management/",
    featured: true,
  },
  {
    id: "economic-growth",
    title: "Crescimento econômico: conceitos e evidências",
    author: "Max Roser e colaboradores",
    source: "Our World in Data",
    type: "Artigo",
    category: "Mundo",
    level: "Intermediário",
    language: "Inglês",
    readTime: "35 min",
    description: "Uma leitura guiada por dados sobre produtividade, renda, pobreza e as grandes diferenças entre países.",
    question: "Qual mecanismo explica o dado, e qual apenas coincide com ele?",
    url: "https://ourworldindata.org/economic-growth",
    featured: true,
  },
  {
    id: "attention-is-all-you-need",
    title: "Attention Is All You Need",
    author: "Ashish Vaswani e colaboradores",
    source: "arXiv",
    type: "Artigo científico",
    category: "Ciência",
    level: "Avançado",
    language: "Inglês",
    readTime: "50 min",
    description: "O artigo que apresentou a arquitetura Transformer, base de grande parte da inteligência artificial generativa atual.",
    question: "Que problema estrutural a atenção resolve melhor que a abordagem anterior?",
    url: "https://arxiv.org/abs/1706.03762",
    featured: true,
  },
  {
    id: "republic-plato",
    title: "A República",
    author: "Platão",
    source: "Project Gutenberg",
    type: "Livro",
    category: "Política",
    level: "Avançado",
    language: "Inglês",
    readTime: "Livro completo",
    description: "O diálogo clássico sobre justiça, educação, poder, caráter e a organização da cidade.",
    question: "Uma sociedade justa depende primeiro de instituições ou de pessoas justas?",
    url: "https://www.gutenberg.org/ebooks/1497",
  },
  {
    id: "wealth-of-nations",
    title: "A Riqueza das Nações",
    author: "Adam Smith",
    source: "Project Gutenberg",
    type: "Livro",
    category: "Negócios",
    level: "Avançado",
    language: "Inglês",
    readTime: "Livro completo",
    description: "Um clássico para estudar divisão do trabalho, produtividade, preços, comércio e instituições econômicas.",
    question: "Quando a especialização aumenta a prosperidade e quando cria fragilidade?",
    url: "https://www.gutenberg.org/ebooks/3300",
  },
  {
    id: "fides-et-ratio",
    title: "Fides et Ratio",
    author: "São João Paulo II",
    source: "Santa Sé",
    type: "Documento",
    category: "Fé",
    level: "Avançado",
    language: "Português",
    readTime: "70 min",
    description: "Uma investigação sobre a cooperação entre fé e razão na busca humana pela verdade.",
    question: "Que tipo de verdade a razão alcança sozinha e onde a fé amplia o horizonte?",
    url: "https://www.vatican.va/content/john-paul-ii/pt/encyclicals/documents/hf_jp-ii_enc_14091998_fides-et-ratio.html",
  },
  {
    id: "centesimus-annus",
    title: "Centesimus Annus",
    author: "São João Paulo II",
    source: "Santa Sé",
    type: "Documento",
    category: "Fé",
    level: "Avançado",
    language: "Português",
    readTime: "60 min",
    description: "Doutrina social, liberdade econômica, Estado, cultura e dignidade humana um século após a Rerum Novarum.",
    question: "Quais limites morais um mercado precisa para servir à pessoa?",
    url: "https://www.vatican.va/content/john-paul-ii/pt/encyclicals/documents/hf_jp-ii_enc_01051991_centesimus-annus.html",
  },
  {
    id: "artemis",
    title: "Artemis: da Lua a Marte",
    author: "NASA",
    source: "NASA",
    type: "Guia",
    category: "Ciência",
    level: "Essencial",
    language: "Inglês",
    readTime: "12 min",
    description: "Visão geral do programa de exploração lunar, sua arquitetura e o caminho tecnológico para missões humanas a Marte.",
    question: "Qual capacidade precisa ser dominada na Lua antes de ser usada em Marte?",
    url: "https://www.nasa.gov/humans-in-space/artemis/",
  },
  {
    id: "exoplanets",
    title: "Mundos além do Sistema Solar",
    author: "NASA Science",
    source: "NASA",
    type: "Artigo",
    category: "Ciência",
    level: "Essencial",
    language: "Inglês",
    readTime: "15 min",
    description: "Uma porta de entrada para a descoberta, classificação e investigação de planetas que orbitam outras estrelas.",
    question: "Como podemos inferir a existência de algo que não vemos diretamente?",
    url: "https://science.nasa.gov/exoplanets/",
  },
  {
    id: "jobs-stanford",
    title: "Conectar os pontos: discurso de Steve Jobs em Stanford",
    author: "Steve Jobs",
    source: "Stanford University",
    type: "Artigo",
    category: "Criação",
    level: "Essencial",
    language: "Inglês",
    readTime: "15 min",
    description: "Três histórias sobre curiosidade, escolhas, perdas e como experiências aparentemente soltas ganham sentido em retrospecto.",
    question: "Quais pontos da sua experiência você ainda não tentou conectar?",
    url: "https://news.stanford.edu/stories/2005/06/youve-got-find-love-jobs-says",
  },
  {
    id: "gates-learning-sessions",
    title: "Aprender com sessões deliberadas e perguntas",
    author: "Bill Gates",
    source: "Gates Notes",
    type: "Artigo",
    category: "Ideias",
    level: "Essencial",
    language: "Inglês",
    readTime: "18 min",
    description: "Perguntas e respostas sobre estudo concentrado, leitura, tecnologia, educação e atualização contínua.",
    question: "Qual pergunta merece um bloco de estudo sem interrupções?",
    url: "https://www.gatesnotes.com/2023-reddit-ama",
  },
  {
    id: "creator-academy",
    title: "Academia de Criadores: estratégia e crescimento",
    author: "YouTube",
    source: "Central de Ajuda do YouTube",
    type: "Guia",
    category: "Criação",
    level: "Essencial",
    language: "Português",
    readTime: "Trilha",
    description: "Guias oficiais sobre planejamento, público, produção, descoberta e análise de desempenho de um canal.",
    question: "Que promessa clara faz alguém escolher seu próximo vídeo?",
    url: "https://support.google.com/youtube/topic/9257894?hl=pt-BR",
  },
  {
    id: "democracy",
    title: "Democracia: medidas, história e diferenças entre países",
    author: "Bastian Herre e colaboradores",
    source: "Our World in Data",
    type: "Artigo",
    category: "Política",
    level: "Intermediário",
    language: "Inglês",
    readTime: "35 min",
    description: "Dados de longo prazo para distinguir conceitos, regimes e mudanças políticas sem depender de impressões isoladas.",
    question: "Como a definição escolhida muda a conclusão de um gráfico político?",
    url: "https://ourworldindata.org/democracy",
  },
  {
    id: "constituicao-brasil",
    title: "Constituição da República Federativa do Brasil",
    author: "Assembleia Nacional Constituinte",
    source: "Presidência da República",
    type: "Documento",
    category: "Política",
    level: "Intermediário",
    language: "Português",
    readTime: "Documento de consulta",
    description: "Texto constitucional oficial para verificar direitos, deveres, instituições e competências antes de discutir a política brasileira.",
    question: "Qual instituição tem competência real para tomar a decisão em debate?",
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
  },
  {
    id: "federalist-papers",
    title: "The Federalist Papers",
    author: "Alexander Hamilton, James Madison e John Jay",
    source: "Project Gutenberg",
    type: "Livro",
    category: "Política",
    level: "Avançado",
    language: "Inglês",
    readTime: "Livro completo",
    description: "Ensaios clássicos sobre separação de poderes, facções, representação e desenho constitucional.",
    question: "Que incentivo institucional limita melhor a concentração de poder?",
    url: "https://www.gutenberg.org/ebooks/1404",
  },
  {
    id: "stoicism",
    title: "Estoicismo",
    author: "Internet Encyclopedia of Philosophy",
    source: "IEP",
    type: "Artigo",
    category: "Ideias",
    level: "Intermediário",
    language: "Inglês",
    readTime: "40 min",
    description: "Panorama acadêmico sobre lógica, física, ética, virtude e a ideia estoica de viver de acordo com a natureza.",
    question: "O que está sob seu juízo, mesmo quando o resultado não está sob seu controle?",
    url: "https://iep.utm.edu/stoicism/",
  },
  {
    id: "managerial-decisions",
    title: "Como gestores tomam decisões",
    author: "OpenStax",
    source: "OpenStax",
    type: "Artigo",
    category: "Negócios",
    level: "Essencial",
    language: "Inglês",
    readTime: "20 min",
    description: "Um capítulo aberto sobre tipos de decisão, incerteza, vieses e responsabilidade gerencial.",
    question: "A decisão é programável ou exige julgamento sob incerteza?",
    url: "https://openstax.org/books/principles-management/pages/2-1-overview-of-managerial-decision-making",
  },
];

export const readingTypes: Array<"Todos" | ReadingType> = ["Todos", "Artigo", "Livro", "Artigo científico", "Documento", "Guia"];
