export type Video = {
  id: string;
  youtubeId: string;
  title: string;
  channel: string;
  topic: string;
  url: string;
  durationSeconds: number;
  depth: number;
  novelty: number;
  quality: number;
  evergreen: number;
  publishedLabel: string;
  palette: "blue" | "coral" | "ink" | "moss" | "violet" | "sand";
  mark: string;
};

export const seedVideos: Video[] = [
  { id: "paulo-ricardo", youtubeId: "canal-padre-paulo-ricardo", title: "Fé, razão e a formação da inteligência cristã", channel: "Pe. Paulo Ricardo", topic: "formação católica", url: "https://www.youtube.com/results?search_query=Padre+Paulo+Ricardo+fé+razão+formação", durationSeconds: 1680, depth: .95, novelty: .66, quality: .97, evergreen: 1, publishedLabel: "trilha de formação", palette: "sand", mark: "FÉ × RAZÃO" },
  { id: "frei-gilson", youtubeId: "UCbh6_TmFnAJLI56aAQeD3qw", title: "Vida de oração, disciplina e combate interior", channel: "Frei Gilson / Som do Monte", topic: "vida espiritual", url: "https://www.youtube.com/channel/UCbh6_TmFnAJLI56aAQeD3qw", durationSeconds: 2100, depth: .84, novelty: .58, quality: .94, evergreen: .98, publishedLabel: "canal oficial", palette: "moss", mark: "ORA ET LABORA" },
  { id: "tomismo", youtubeId: "tomismo", title: "O que Aristóteles e São Tomás ensinam sobre a vida boa", channel: "Formação clássica", topic: "filosofia", url: "https://www.youtube.com/results?search_query=Aristóteles+São+Tomás+vida+boa+aula", durationSeconds: 2480, depth: .97, novelty: .72, quality: .91, evergreen: 1, publishedLabel: "aula longa", palette: "ink", mark: "VERUM" },
  { id: "natureza-humana", youtubeId: "natureza-humana", title: "Por que pessoas boas tomam decisões ruins?", channel: "Psicologia & natureza humana", topic: "natureza humana", url: "https://www.youtube.com/results?search_query=natureza+humana+decisões+psicologia+aula", durationSeconds: 1320, depth: .88, novelty: .86, quality: .9, evergreen: .97, publishedLabel: "ensaio", palette: "violet", mark: "QUEM SOMOS?" },
  { id: "economia-incentivos", youtubeId: "economia-incentivos", title: "Incentivos: a força invisível por trás da economia", channel: "Economia em perspectiva", topic: "economia", url: "https://www.youtube.com/results?search_query=economia+incentivos+aula+português", durationSeconds: 1120, depth: .91, novelty: .75, quality: .93, evergreen: .98, publishedLabel: "aula essencial", palette: "blue", mark: "↗ $ ↘" },
  { id: "gestao-cultura", youtubeId: "gestao-cultura", title: "Cultura não é um pôster: como organizações realmente funcionam", channel: "Gestão & estratégia", topic: "gestão", url: "https://www.youtube.com/results?search_query=cultura+organizacional+gestão+aula", durationSeconds: 1890, depth: .86, novelty: .78, quality: .91, evergreen: .94, publishedLabel: "estudo de caso", palette: "coral", mark: "CULTURA > PLANO" },
  { id: "geopolitica", youtubeId: "geopolitica", title: "Como geografia, energia e demografia moldam o poder", channel: "Geopolítica em camadas", topic: "geopolítica", url: "https://www.youtube.com/results?search_query=geopolítica+geografia+energia+demografia+aula", durationSeconds: 2640, depth: .94, novelty: .88, quality: .92, evergreen: .9, publishedLabel: "aula panorâmica", palette: "moss", mark: "TERRA → PODER" },
  { id: "politica-ideias", youtubeId: "politica-ideias", title: "Conservador, liberal, socialista: ideias antes dos rótulos", channel: "História das ideias políticas", topic: "política", url: "https://www.youtube.com/results?search_query=história+das+ideias+políticas+conservadorismo+liberalismo+socialismo+aula", durationSeconds: 2380, depth: .96, novelty: .82, quality: .92, evergreen: .97, publishedLabel: "perspectivas comparadas", palette: "coral", mark: "IDEIAS ≠ TRIBOS" },
  { id: "estrategia", youtubeId: "estrategia", title: "Estratégia é escolher: o que uma empresa precisa recusar", channel: "Administração sem atalhos", topic: "administração", url: "https://www.youtube.com/results?search_query=Michael+Porter+estratégia+escolhas+aula+português", durationSeconds: 1560, depth: .9, novelty: .7, quality: .94, evergreen: .98, publishedLabel: "fundamentos", palette: "blue", mark: "ESCOLHER = RECUSAR" },
  { id: "empreendedor", youtubeId: "empreendedor", title: "Negócios duradouros resolvem problemas reais", channel: "Empreendedorismo responsável", topic: "negócios", url: "https://www.youtube.com/results?search_query=negócios+duradouros+empreendedorismo+aula", durationSeconds: 1440, depth: .82, novelty: .74, quality: .89, evergreen: .92, publishedLabel: "conversa de negócios", palette: "sand", mark: "VALOR > HYPE" },
  { id: "doutrina-social", youtubeId: "doutrina-social", title: "Pessoa, trabalho e bem comum na Doutrina Social da Igreja", channel: "Formação católica", topic: "teologia", url: "https://www.youtube.com/results?search_query=doutrina+social+da+igreja+trabalho+bem+comum+aula", durationSeconds: 2220, depth: .94, novelty: .79, quality: .94, evergreen: 1, publishedLabel: "formação", palette: "sand", mark: "BEM COMUM" },
  { id: "historia-brasil", youtubeId: "historia-brasil", title: "O Brasil explicado pelas instituições que construiu", channel: "História política do Brasil", topic: "história", url: "https://www.youtube.com/results?search_query=história+instituições+políticas+brasil+aula", durationSeconds: 2760, depth: .93, novelty: .84, quality: .91, evergreen: .95, publishedLabel: "curso aberto", palette: "ink", mark: "BRASIL, POR QUÊ?" },
  { id: "roteiro", youtubeId: "roteiro", title: "Roteiros que sustentam atenção sem apelar para distração", channel: "Estratégia de conteúdo", topic: "roteiro", url: "https://www.youtube.com/results?search_query=como+escrever+roteiro+youtube+storytelling+aula", durationSeconds: 1260, depth: .88, novelty: .82, quality: .92, evergreen: .94, publishedLabel: "oficina prática", palette: "coral", mark: "TENSÃO → IDEIA" },
  { id: "canal", youtubeId: "canal", title: "Como planejar um canal com uma tese editorial clara", channel: "Criadores que pensam", topic: "estratégia de canal", url: "https://www.youtube.com/results?search_query=estratégia+canal+youtube+planejamento+editorial", durationSeconds: 1740, depth: .86, novelty: .79, quality: .9, evergreen: .92, publishedLabel: "planejamento", palette: "blue", mark: "1 CANAL · 1 TESE" },
  { id: "producao", youtubeId: "producao", title: "Do tema à publicação: um sistema de produção de vídeos", channel: "Processo criativo", topic: "criação de vídeos", url: "https://www.youtube.com/results?search_query=workflow+produção+vídeos+youtube+planejamento", durationSeconds: 1480, depth: .82, novelty: .74, quality: .89, evergreen: .9, publishedLabel: "guia de processo", palette: "sand", mark: "IDEIA → VÍDEO" },
  { id: "foguetes", youtubeId: "foguetes", title: "Como um foguete chega à órbita — e por que não basta subir", channel: "Astronomia & espaço", topic: "foguetes", url: "https://www.youtube.com/results?search_query=como+foguete+entra+em+órbita+astronomia+português", durationSeconds: 980, depth: .79, novelty: .9, quality: .93, evergreen: .96, publishedLabel: "aula visual", palette: "ink", mark: "Δv → ÓRBITA" },
  { id: "cosmos", youtubeId: "cosmos", title: "A escala do universo em uma viagem de poucos minutos", channel: "Curiosidades do cosmos", topic: "astronomia", url: "https://www.youtube.com/results?search_query=escala+do+universo+astronomia+português", durationSeconds: 720, depth: .72, novelty: .96, quality: .94, evergreen: .98, publishedLabel: "exploração", palette: "violet", mark: "10²⁶ m" },
  { id: "empresas", youtubeId: "empresas", title: "Por que grandes empresas perdem para ideias pequenas", channel: "Histórias de empresas", topic: "negócios", url: "https://www.youtube.com/results?search_query=empresas+inovação+dilema+do+inovador+aula", durationSeconds: 1340, depth: .86, novelty: .87, quality: .91, evergreen: .93, publishedLabel: "estudo de caso", palette: "moss", mark: "GRANDE ≠ ÁGIL" },
  { id: "curiosidades", youtubeId: "curiosidades", title: "Sete perguntas simples que abrem ideias enormes", channel: "Curiosidades que ensinam", topic: "curiosidades", url: "https://www.youtube.com/results?search_query=curiosidades+ciência+perguntas+explicadas+português", durationSeconds: 840, depth: .7, novelty: .98, quality: .88, evergreen: .95, publishedLabel: "coleção", palette: "coral", mark: "POR QUÊ?" },
];
