import assert from "node:assert/strict";
import { loadLocalTs } from "./lib/load-local-ts.mjs";

const { emptyHabitStore, parseHabitStore, weeklyReview, formatBedtime, bedtimeMinutes, isMinimumWindow, dispositionSeries, createHabitDemo, reviewMarkdown, RETURN_MESSAGE, addDays } = loadLocalTs("lib/habits.ts");
const store = emptyHabitStore("2026-09-01");
assert.throws(() => parseHabitStore("{broken"));
assert.throws(() => parseHabitStore('{"version":2}'));
for (const [date, bedtime] of [["2026-09-07", "23:00"], ["2026-09-08", "01:00"]]) store.entries[date] = { date, bedtime, pages: 0, instagramMinutes: 0, disposition: 0, hobbySpend: 0 };
store.entries["2026-09-09"] = { date: "2026-09-09" };
const review = weeklyReview(store, "2026-09-09", "2026-09-13");
assert.equal(review.start, "2026-09-07");
assert.equal(review.end, "2026-09-13");
assert.equal(review.recordedDays, 3);
assert.equal(review.instagramCount, 2);
assert.equal(review.instagramAverage, 0);
assert.equal(review.dispositionAverage, 0);
assert.equal(review.pagesAverage, 0);
assert.equal(review.readingDays, 0);
assert.equal(review.monthlySpend, 0);
assert.equal(formatBedtime(review.bedtimeAverage), "00:00");
assert(bedtimeMinutes("00:30") > bedtimeMinutes("23:00"));
assert.equal(weeklyReview(emptyHabitStore(), "2026-09-09", "2026-09-13").instagramAverage, null);
assert.equal(weeklyReview(emptyHabitStore(), "2026-09-09", "2026-09-13").monthlySpend, null);
assert.equal(weeklyReview(store, "2026-09-09", "2026-09-09").elapsedDays, 3);
assert(!isMinimumWindow("2026-09-09", store.settings));
assert(isMinimumWindow("2026-09-10", store.settings));
assert(isMinimumWindow("2026-09-25", store.settings));
assert(!isMinimumWindow("2026-09-26", store.settings));
assert.equal(addDays("2026-12-31", 1), "2027-01-01");
assert.equal(addDays("2024-02-28", 1), "2024-02-29");
const restored = parseHabitStore(JSON.stringify(store));
assert.equal(restored.entries["2026-09-07"].pages, 0);
assert.equal(restored.entries["2026-09-09"].pages, undefined);

const demo = createHabitDemo();
assert.equal(Object.keys(demo.entries).length, 16);
const weeks = ["2026-09-06", "2026-09-13", "2026-09-20"].map((date) => ({ date, ...weeklyReview(demo, date, "2026-09-20") }));
assert.equal(weeks.map((week) => week.recordedDays).join(","), "5,6,5");
assert.equal(weeks[2].monthlySpend, 270);
assert.equal(weeks[2].installments.length, 1);
assert.equal(weeks[2].minimumDays, 3);
const series = dispositionSeries(demo, "2026-09-20");
assert.equal(series.length, 21);
assert.equal(series.filter((point) => point.value === null).length, 5);
assert.equal(series.filter((point) => point.minimum).length, 12);
const markdown = reviewMarkdown(demo, "2026-09-20", "2026-09-20");
assert(markdown.includes("sem registro"));
assert(markdown.includes(RETURN_MESSAGE));
assert(markdown.includes("meta cumprida (versão mínima)"));
console.table(weeks.map((week) => ({ week: `${week.start} a ${week.end}`, recorded: week.recordedDays, instagram: week.instagramAverage?.toFixed(1), bedtime: formatBedtime(week.bedtimeAverage), readingDays: week.readingDays, minimumDays: week.minimumDays, monthlySpend: week.monthlySpend, installments: week.installments.length })));
console.log("Testes de datas, médias, ausência vs. zero, meia-noite, orçamento, versão mínima e exportação: OK. Demonstração: 21 dias, 16 registros e 5 lacunas.");
if (process.argv.includes("--markdown")) console.log(markdown);
